### ISSUE TITLE
Pull Request access

### ISSUE THREAD

**Issue by nospoon4u** [mjisaak/AzureStorageHostedAngularApp#1]
I added a small usability update to your ARMTemplate, but was denied pushing up my change. I'd like to do a Pull Request for your review.

**Comment by mjisaak** [comment]
@nospoon4u I really appreciate your intention to contribute on this repository. This is how you can create a Pull Request:

Fork the repository
Clone it to your local system.
Make a new branch.
Make your changes.
Push it back to your repo.
Click the Compare & pull request button.
Click Create pull request to open a new pull request.

Hope this helps. 
Best regards,
Martin

**Comment by nospoon4u** [comment]
I forgot to fork :)
